### PR TITLE
Fix statistics method due to API change

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** This changes fixes the statistics method defined for `lightning.gpu` due to https://github.com/PennyLaneAI/pennylane/pull/2820 change in the `_qubit_device` API.

**Description of the Change:** Adds additional keyword arg to avoid failures in tests.

**Benefits:** `pl-device-tests` no longer fail with `lightning.gpu`

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by chaeyeunpark — APPROVED** [review]
Thanks @mlxd for the quick fix!

**Review by albi3ro — APPROVED** [review]
Looks good.

**Comment by mlxd** [comment]
Thanks folks!

**Review by AmintorDusko — APPROVED** [review]
Thank you for that!

**Pull request merged**
