### PR TITLE
Downgrade Numpy to avoid conflicts

### PR DESCRIPTION
**Pull request by AmintorDusko**
**Context:** Numpy last minor version 1.24 has some conflicts with Autograd.

**Description of the Change:** For now we'll limit installation to Numpy < 1.24

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by AmintorDusko** [comment]
All changes are in the initial commit.

**Comment by AmintorDusko** [comment]
We'll need PR #88 to be merged first.

**Comment by mlxd** [comment]
PR https://github.com/PennyLaneAI/pennylane-lightning-gpu/pull/88 approved. once merged, will approve this.

**Comment by multiphaseCFD** [comment]
> We'll need PR #88 to be merged first.

Thanks @AmintorDusko ! Happy to approve it once all tests passed.

**Comment by josh146** [comment]
I discovered the other day that there is an update to Autograd (1.5 I think) that fixes this clash! Did you try updating the autograd version?

**Comment by AmintorDusko** [comment]
> I discovered the other day that there is an update to Autograd (1.5 I think) that fixes this clash! Did you try updating the autograd version?

Hi @josh146, we rely on PennyLane Autograd and Numpy requirements.
If we, for example, install numpy 1.24.1 for any lightning repository, the requirement parser will identify a conflict with the pennylane package requirement (numpy<1.24).

**Comment by josh146** [comment]
Thanks @AmintorDusko, I was mistaken/forgot about this - my fault! You are correct

**Review by multiphaseCFD — APPROVED** [review]

**Review by mlxd — APPROVED** [review]

**Pull request merged**
